### PR TITLE
Added Debian instructions, fixed ordering

### PR DESCRIPTION
**Pull request by barnumbirr**

### CODE REVIEW

**Comment by dandavison** [comment]
Thanks @barnumbirr! I agree about fixing the ordering :). 

Wow, thanks for creating [delta-debian](https://github.com/barnumbirr/delta-debian). The delta travis script is currently building some .debs:

https://github.com/dandavison/delta/blob/master/ci/before_deploy.sh#L52
https://github.com/dandavison/delta/releases/tag/0.1.1

What would we need to change in the delta repo to publish an appropriate set of .debs on release?

**Comment by barnumbirr** [comment]
Hey @dandavison ,

glad you agree. If you don't want to have the Debian packages to be built in an external repository, you could just use the `debian` directory in [barnumbirr/delta-debian](https://github.com/barnumbirr/delta-debian) and build the `.deb`'s with it on Travis.
You'd probably need to tweak the current setup quite a bit to be able to build the three flavors but I'm more than happy to help if you need a hand.

Cheers.

**Comment by dandavison** [comment]
It's been a while since I administered my own debian/ubuntu system. Would you mind explaining to me what we've got in the union of both sets of .debs? So specifically, suppose someone is in possession of either (a) the set of .debs I am releasing, or (b) the set of .debs you are releasing. And suppose that person has (I) a Debian system, (II) an Ubuntu system. What are the things they could and could not do in each case? For example I see your .debs are for one architecture only.

If there is any chance that you wouldn't mind explaining the situation to me that would be very much appreciated!

### (a)
- git-delta_0.1.1_armhf.deb
- git-delta_0.1.1_amd64.deb
- git-delta-musl_0.1.1_amd64.deb
- git-delta_0.1.1_i386.deb


### (b)
- delta_0.1.1-1_amd64_debian_{buster,testing,unstable}.deb

**Comment by barnumbirr** [comment]
Hi,

I guess the gist is that you're building the package for more architectures, I'm trying to build packages for more Debian versions. I haven't tested it so I have no idea if your package actually runs on Buster/testing/unstable.

Cheers.

**Comment by dandavison** [comment]
Thanks! I modified this PR to link to both sources of .debs. How shall we coordinate new releases ?

**Comment by barnumbirr** [comment]
That works as well 👌 I've subscribed to new `delta` releases so I'll keep the packages up to date. 

Cheers.

**Comment by dandavison** [comment]
Awesome, thanks very much for this.

**Pull request merged**
