### PR TITLE
Temp modification to CD action to bump homebrew formula

### PR DESCRIPTION
**Pull request by dandavison**
cc @MarcoIeni in case you have ideas -- having a little difficulty getting `bump-homebrew-formula` to work.

(By the way your CD changes otherwise worked flawlessly and just released the new version!)

```
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:273:in `raise_api_error': GitHub Resource not accessible by integration:HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check: (GitHub::AuthenticationFailedError)
  https://github.com/settings/tokens
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:223:in `open_api'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:72:in `<module:Homebrew>'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:17:in `<main>'
Error: Process completed with exit code 1.
```

<table><tr><td>image</td></tr></table>

### CODE REVIEW

**Comment by dandavison** [comment]
I believe the token is valid: this succeeds
```
curl -H "Authorization: token ${HOMEBREW_GITHUB_API_TOKEN}" https://api.github.com/users/dandavison
```

and the response from

```
curl -I -H "Authorization: token ${HOMEBREW_GITHUB_API_TOKEN}" https://api.github.com/users/dandavison
```

contains

```
X-OAuth-Scopes: gist, repo, user, workflow
X-Accepted-OAuth-Scopes: 
```

**Comment by MarcoIeni** [comment]
https://github.com/dandavison/delta/blob/c46d3328af0cfb0adcb1642c88db98e84d39b4ff/.github/workflows/cd.yml#L93

Maybe you have to pass the right token here?

**Comment by MarcoIeni** [comment]
This PR can be closed because the issue was solved by 9e53f520440c38dc3b3dc21b9e68b1b2c2509179 I think

**Comment by dandavison** [comment]
> This PR can be closed because the issue was solved by 9e53f52 I think

Yep, thanks for that.

**Pull request closed without merging**
