### PR TITLE
Support SVN diff output

### LINKED ISSUE #105: svn diff is not supported
svn diff | delta

Delta behaves as less.

Does it support plain diff format?

### PR DESCRIPTION
**Pull request by dandavison**
WIP, would fix #105 cc @Yanpas

image

### CODE REVIEW

**Comment by dandavison** [comment]
- [ ] Prevent deletion of the first character of "Index: " lines  (it's being deleted because in normal git output it would be a `+/-` indicator, which delta does not emit.

**Comment by Yanpas** [comment]
Svn alreay may show property changes in diff but I don't think it's worth supporting them, delta just skips them.

```
$ svn merge ^/branches/b1
--- Recording mergeinfo for merge of r12 through r14 into '.':
 U   .
yan@yPC:~/pg/foo/trunk$ svn diff 
Index: .
===================================================================
--- .   (revision 14)
+++ .   (working copy)

Property changes on: .
___________________________________________________________________
Added: svn:mergeinfo
## -0,0 +0,1 ##
   Merged /branches/b1:r12-14
yan@yPC:~/pg/foo/trunk$ svn diff | ~/opensource/delta/t
target/  testing/ 
yan@yPC:~/pg/foo/trunk$ svn diff | ~/opensource/delta/target/debug/delta 
Index: .
===================================================================

comparing: . ⟶   .
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
yan@yPC:~/pg/foo/trunk$ ls
f1  file.c
yan@yPC:~/pg/foo/trunk$ echo aaa >> file.c 
yan@yPC:~/pg/foo/trunk$ svn diff 
Index: file.c
===================================================================
--- file.c      (revision 14)
+++ file.c      (working copy)
@@ -1 +1,2 @@
 void aa(){}
+aaa
Index: .
===================================================================
--- .   (revision 14)
+++ .   (working copy)

Property changes on: .
___________________________________________________________________
Added: svn:mergeinfo
## -0,0 +0,1 ##
   Merged /branches/b1:r12-14
yan@yPC:~/pg/foo/trunk$ svn diff | ~/opensource/delta/target/debug/delta 
Index: file.c
===================================================================

comparing: file.c ⟶   file.c
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

1
 void aa(){}                                                                                                                                                                                                      
 aaa                                                                                                                                                                                                              
 ndex: .                                                                                                                                                                                                          
 ==================================================================                                                                                                                                               

comparing: . ⟶   .
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by Minnozz** [comment]
Hi! I'm a subversion user and would love to use this feature; can you use help on this PR?

**Comment by dandavison** [comment]
> Hi! I'm a subversion user and would love to use this feature; can you use help on this PR?

Hi @Minnozz, sorry I forgot to reply to this. Absolutely, help with SVN support would be very welcome. I think the only reason I hesitated here was that I wasn't sure how many subversion users there were, and I was already conscious that the main diff-parsing loop in delta.rs wasn't very cleanly written. But, it's got a bit better since February and maybe I've come to terms with it :)

**Comment by dandavison** [comment]
Inactive, could always revisit.

**Pull request closed without merging**
