### PR TITLE
CI: add code coverage

### PR DESCRIPTION
**Pull request by MarcoIeni**
Solves #401

### CODE REVIEW

**Comment by dandavison** [comment]
🚀  awesome! Thanks, @MarcoIeni! I'm excited about this one (I have no idea what the coverage looks like, but I'm very interested to find out).

**Comment by dandavison** [comment]
Very interesting and helpful: https://coveralls.io/github/dandavison/delta?branch=master

**Comment by dandavison** [comment]
By the way, are you intending to go all the way and get the release build matrix running in Github Actions? (That would of course be fantastic if so.)

**Comment by MarcoIeni** [comment]
Sure!

**Pull request merged**
