### PR TITLE
Add new theme mantis-shrimp

### PR DESCRIPTION
**Pull request by 2KAbhishek**
*colourful and deadly*

### CODE REVIEW

**Comment by dandavison** [comment]
Hi @2KAbhishek, thanks! Would you be able to post a screenshot?

**Comment by 2KAbhishek** [comment]
> Hi @2KAbhishek, thanks! Would you be able to post a screenshot?

image


here's the screenshot @dandavison

**Comment by dandavison** [comment]
Ah, very nice! Thanks!

**Comment by 2KAbhishek** [comment]
> Ah, very nice! Thanks!

No, thank you for making this awesome tool :D

**Pull request merged**
