### PR TITLE
Make hunk header code fragment display optional

### PR DESCRIPTION
**Pull request by zmc**
Fixes: #1032

### CODE REVIEW

**Comment by dandavison** [comment]
Nice, very clean. Thanks a lot for doing this!

**Comment by zmc** [comment]
Thanks for delta!

**Comment by Jelloeater** [comment]
@zmc Any idea when this is going to make it into release? Really excited to have clean output in tiny windows heh heh.

**Comment by zmc** [comment]
@Jelloeater sorry, I don't have any idea but I'm glad you like the feature! Maybe try building the project from source so you don't have to wait? 😉

**Comment by dandavison** [comment]
Yes, sorry for the delay releasing, but I  can confirm that building from source should be easy. There are instructions here, but there's not much to say: https://dandavison.github.io/delta/build-delta-from-source.html

**Comment by Jelloeater** [comment]
I can wait, it's not the end of the world ❤️

**Pull request merged**
