### PR TITLE
Remove `-style` suffix for delta colours

### PR DESCRIPTION
**Pull request by srasku**
If you append the `-color` suffix you get the following error:
    - Invalid color or style attribute:

### CODE REVIEW

**Comment by dandavison** [comment]
Hi @srasku, thanks! So, hang on, I'm slightly confused. It's true that `minus-color` is incorrect. The correct form is `minus-style`. But your diff is changing it to just `minus`, which isn't correct.

**Comment by srasku** [comment]
@dandavison, I made an error in the commit message.  The headline is correct but the body is wrong.  The whole thing should read:
> Remove `-style` suffix for delta colours
>
>If you append the `-style` suffix you get the following error:
>    - Invalid color or style attribute:

I do get the error message specified unless I remove the suffix.
```
(venv) stephenrasku@CLIR-00161 Code/clir 691 $ cat ~/.gitconfig
...
[core]
	pager = delta
	excludesfile = ~/.gitignore_global
[interactive]
	diffFilter = delta --color-only
[delta]
	navigate = true
	minus-style = red bold ul '#ffeeee'
[merge]
	conflictstyle = diff3
[diff]
	colorMoved = default
(venv) $ git diff
Invalid color or style attribute: 
(venv) $ cat ~/.gitconfig
...
	pager = delta
	excludesfile = ~/.gitignore_global
[interactive]
	diffFilter = delta --color-only
[delta]
	navigate = true
	minus = red bold ul '#ffeeee'
[merge]
	conflictstyle = diff3
[diff]
	colorMoved = default
(venv) $ git diff
(venv) $
```

**Comment by dandavison** [comment]
Hi @srasku, the problem is that you're using single quote characters around your color. If you change that to `red bold ul "#ffeeee"` it works. The reason you didn't see an error with `minus` is that `minus` isn't a value that delta recognizes! But `minus-style` is the correct form: https://github.com/dandavison/delta/blob/3ccf2bc8d26b9296a08110d9ac7bc60d86bbeaa6/src/cli.rs#L797

**Comment by srasku** [comment]
Yes, I can confirm this is the issue.  Thanks for clearing it up.

**Pull request closed without merging**
