### PR TITLE
add a sample delta theme to `themes.gitconfig`

### PR DESCRIPTION
**Pull request by Kr1ss-XD**
Starting with a first example style, reflecting what I use personally.

### CODE REVIEW

**Comment by dandavison** [comment]
Awesome, thanks @Kr1ss-XD! Would you be able to post a screenshot, and also describe the terminal color theme that you tend to use with this?

**Comment by Kr1ss-XD** [comment]
Sure.

Screenshot

`~/.config/xfce4/terminal/terminalrc` (excerpt with only the color settings)

```
[...]
ColorForeground=#d3d3d7d7cfcf
ColorBackground=#000004040000
ColorCursorUseDefault=FALSE
ColorCursorForeground=#02010000baba
ColorCursor=#ffffdedd5352
ColorSelectionUseDefault=FALSE
ColorSelection=#02010000baba
ColorSelectionBackground=#fcfce9e94f4f
ColorPalette=rgb(32,32,32);rgb(232,0,0);rgb(0,170,0);rgb(220,178,29);rgb(30,48,255);rgb(225,0,134);rgb(31,213,169);rgb(187,187,187);rgb(80,80,80);rgb(255,64,22);rgb(0,255,0);rgb(255,228,0);rgb(64,128,255);rgb(255,82,144);rgb(0,255,194);rgb(238,238,236)
[...]
```

**Comment by dandavison** [comment]
Thanks for this @Kr1ss-XD!

(Just for the record, the colors didn't render correctly for me the first time I tried, but that's because I was using tmux and I think italics ANSI codes don't work with tmux, or  tmux and iTerm2.)

**Comment by Kr1ss-XD** [comment]
Thank you for the quick response !

>the colors didn't render correctly for me the first time I tried, but that's because I was using tmux and I think italics ANSI codes don't work with tmux, or tmux and iTerm2.

That must be caused by the different terminal emulators we use then, most likely, as I'm also using tmux.

**Pull request merged**
