### PR TITLE
Add Winget Releaser workflow

### PR DESCRIPTION
**Pull request by sitiom**
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Delta has recently been added to Winget (https://github.com/microsoft/winget-pkgs/pull/94791), and this workflow will be used to keep it up to date.

**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @dandavison. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been created with WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+created+with+WinGet+Releaser).

### CODE REVIEW

**Comment by dandavison** [comment]
Thanks! I think I followed your instructions; let me know if it works!

**Comment by sitiom** [comment]
We'll know if it works on the next release 🙂

**Comment by dandavison** [comment]
Hi @sitiom, it looks like it partially worked? I got an email, but on the other hand this build failed: https://github.com/dandavison/delta/actions/runs/5160535447/jobs/9296756572

**Comment by sitiom** [comment]
Well seems like it did work? https://github.com/microsoft/winget-pkgs/pull/108812

But this is something to look upon 🤔

**Comment by sitiom** [comment]
Well seems like it did work? https://github.com/microsoft/winget-pkgs/pull/108812

But this is something to look upon 🤔 @vedantmgoyal2009

**Pull request merged**
