### PR TITLE
Add support for `hg log --patch`

### PR DESCRIPTION
**Pull request by Tak**

### CODE REVIEW

**Comment by dandavison** [comment]
Hi @Tak, thanks very much for the careful PR with test coverage. I'm sorry I overlooked it while I was traveling; I'll merge it soon. (I've made a mess of the branch by merging in master; I'll sort that out, probably with a force push to this branch assuming I have perms to do so, but you don't need to do anything.)

**Comment by Tak** [comment]
If you want, I can rebase my local branch on top of your master and repush, whatever's easier for you

**Comment by dandavison** [comment]
If you feel like cleaning it up, feel free!

**Comment by Tak** [comment]
✅

**Comment by Tak** [comment]
Stale/obsolete

**Pull request closed without merging**
