### PR TITLE
add Continuous delivery

### PR DESCRIPTION
**Pull request by MarcoIeni**
Result: https://github.com/MarcoIeni/delta/releases/tag/0.4.15

### CODE REVIEW

**Comment by dandavison** [comment]
🚀 👏 Thanks so much @MarcoIeni, this has been a fantastic series of PRs! The testing is more robust, we have coverage, and now we have CI and CD in GitHub actions. This is really a huge help to the project and will be for years to come.

**Comment by MarcoIeni** [comment]
It has been really funny and I learned a lot.
Thank you for reviewing my PRs so fast :)

**Comment by dandavison** [comment]
This time it looks like absolutely everything worked, including publish to crates.io and bump homebrew formula 😃  https://github.com/dandavison/delta/actions/runs/453636197

**Comment by MarcoIeni** [comment]
Nice! 😎

**Pull request merged**
