### PR TITLE
Add snap recipe

### PR DESCRIPTION
**Pull request by alexmurray**
This allows to create and publish https://snapcraft.io snap packages for Linux - you can easily setup automatic builds + publishing via https://build.snapcraft.io as well

### CODE REVIEW

**Comment by dandavison** [comment]
Hi @alexmurray, I'm sorry this got forgotten. Other than merging this PR, what else would have to be done?

**Comment by alexmurray** [comment]
Hey @dandavison, after merging the PR the next step would be to create an account on https://snapcraft.io via https://login.ubuntu.com - once this is done, then you can register the snap and set it up to build automatically from the github repo - see https://snapcraft.io/build for more info

**Comment by alexmurray** [comment]
Note I am not sure if the current snapcraft.yaml recipe is still functional so this may need some tweaks to build successfully but I can help with that if needed too.

**Comment by dandavison** [comment]
Sorry this got ignored. We could go with https://github.com/dandavison/delta/pull/1542 if there is interest in this.

**Pull request closed without merging**
