### PR TITLE
Replace unmaintained/outdated GitHub Actions

### PR DESCRIPTION
**Pull request by nickelc**
The unmaintained `action-rs/*` actions are replaced with `dtolnay/rust-toolchain`, `taiki-e/install-action` and plain cargo commands.

### CODE REVIEW

**Comment by dandavison** [comment]
Thanks again! Can you explain how you've tested this?

**Comment by nickelc** [comment]
I pushed the changes into my `master` branch.
See https://github.com/nickelc/delta/actions?query=branch%3Amaster

**Comment by dandavison** [comment]
> I pushed the changes into my master branch.

Great, I test Github Actions in other people's projects by forking the repo; I wasn't sure if that was how others do it. I'll merge this when the tests pass.

**Comment by dandavison** [comment]
Hi @nickelc and @MarcoIeni. `ubuntu-latest` cross-compilation builds are failing and I was wondering whether either of you have any ideas?

In order to try to get a release out, I have deleted the cross compilation targets in the commits below. The commit messages link to failing GitHub actions builds. 

https://github.com/dandavison/delta/commit/9a2fa348eb4470a73790cc24320f1964783264c4
https://github.com/dandavison/delta/commit/eebddddb0a8c41f1225d9cd9a50d70128642623f
https://github.com/dandavison/delta/commit/4af8adf580818b57baa062bb7cd89a1cb72f1fbb
https://github.com/dandavison/delta/commit/2937f3277a10d660bdb920ee6d5b9f033f6d97ef

But obviously I'd like to have those binaries working again.

Thanks for all your past help!

**Comment by nickelc** [comment]
@dandavison I've created a PR to fix the cross-compilation but I'm not familiar with the WinGet part.
- #1430

**Pull request merged**
