### PR TITLE
Add link to similar project walles/riff

### PR DESCRIPTION
**Pull request by walles**
Add link to similar project <http://github.com/walles/riff>.

### CODE REVIEW

**Comment by dandavison** [comment]
Hi @walles, LGTM! Did you mean to take this out of Draft mode? moar looks interesting and a fun thing to work on; any plans to support hyperlinks?

**Comment by walles** [comment]
> Did you mean to take this out of Draft mode?

Done!

Usually I try to do that after CI passes to not bother maintainers with broken code, but nowadays GitHub won't run CI for new contributors so my tactics need updating here it seems.

**Comment by walles** [comment]
> moar looks interesting and a fun thing to work on; any plans to support hyperlinks?

In a lot of terminals you can <kbd>cmd</kbd>-click links to follow them anyway, so I'm unsure what `moar` could potentially do to support them better.

But this conversation might be a better fit for <https://github.com/walles/moar/issues> 😄

**Comment by dandavison** [comment]
Oh sorry, yes I meant [OSC8 hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda), which delta uses to create links to commits on web hosting platforms, and links to specific lines of code from the diff so that they can be opened in IDEs/editors with a click. I think moar doesn't yet handle the ANSI sequences involved; at least they were displayed raw when I tried moar with delta.

**Pull request merged**
