### PR TITLE
README: Add Fedora instructions

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Those are still in updates-testing for F31/F32, but should be pushed to stable in a few days.

### CODE REVIEW

**Comment by dandavison** [comment]
Great thanks! Does it make sense to merge this in a few days?

**Comment by ignatenkobrain** [comment]
Up to you :)

Follow those updates here:

* [F31](https://bodhi.fedoraproject.org/updates/FEDORA-2020-7d10a3490d)
* [F32](https://bodhi.fedoraproject.org/updates/FEDORA-2020-2441d8c17d)

**Comment by ignatenkobrain** [comment]
@dandavison both updates has been pushed to stable, so they are available for everyone by default.

**Comment by dandavison** [comment]
Thanks for doing this!

**Pull request merged**
