### PR TITLE
Make sure rename only shows up once

### PR DESCRIPTION
**Pull request by m-lima**
If files are renamed and modified, `delta` will output the renaming twice.
For instance, given the following `git diff` output:

```
diff --git a/one.rs b/two.rs
similarity index 99%
rename from one.rs
rename to two.rs
index 50fc1ba..37f64c4 100644
--- a/one.rs
+++ b/two.rs
@@ -19,7 +19,6 @@
 ### Examples

 These are changes:
-one:
+two:
```

then `renamed: one.rs ⟶   two.rs` will show up twice

This PR assess that by resetting the file names on each `FileMeta` state entry.

### CODE REVIEW

**Comment by dandavison** [comment]
Thanks for this and #56! I'll try to review them soon.

**Comment by dandavison** [comment]
@m-lima could you merge, or rebase on, master here?

**Comment by waldyrious** [comment]
This has now been fixed in c68bb01.

**Comment by dandavison** [comment]
Thanks @waldyrious and @m-lima. I'm not quite sure why I let this PR stagnate but as @waldyrious says we should have the functionality now.

**Pull request closed without merging**
